### ISSUE TITLE
New Versions are not being imported due to the use of AppDmgVersioner

### ISSUE THREAD

**Issue by andredb90** [autopkg/peshay-recipes#41]
With CFBundleShortVersionString not being updated in latest releases. The recipe does not import the newest version of the app. 
Please use Versioner instead of AppDmgVersioner, which can be configured to read CFBundleVersion.

**Comment by roratonet** [comment]
I see two issues here:

1) To use Versioner I would need to specify the full path including the app name (AppName.app). If AppName changes, I need to change the recipe.
2) I've verified "CFBundleVersion" on some apps I'm deploying and it's not that human readable:
Slack.app
	<key>CFBundleVersion</key>
	<string>6208</string>
	<key>CFBundleShortVersionString</key>
	<string>4.2.0</string>
Google Chrome.app
	<key>CFBundleVersion</key>
	<string>3987.87</string>
	<key>CFBundleShortVersionString</key>
	<string>80.0.3987.87</string>

Therefore I'm not for changing this behaviour if I won't get the correct version from all the apps I'm deploying.

**Comment by andredb90** [comment]
Thank you.

My main concern only applies to Skype.filewave recipe. (I now know that I should have opened a PR instead)

I agree, this change is not necessary for most Apps. For Skype, however, it's is not importing the latest version because Microsoft does not update `CFBundleShortVersionString` on minor releases.

**Comment by roratonet** [comment]
@andredb90 I've fixed the Skype.filewave.recipe replacing AppDmgVersioner with Versioner.

**Comment by andredb90** [comment]
Thank you. I am now receiving the latest Skype version as expected. 

I'm seeing the same issue with "Opera.filewave.recipe" 

CFBundleShortVersionString
67.0
CFBundleVersion
67.0.3575.97

After the Update:

CFBundleShortVersionString
67.0 (is still the same and the app remains to be outdated) 
CFBundleVersion
67.0.3575.115

**Comment by roratonet** [comment]
@andredb90 thank you!
I've updated this recipe.

**Comment by andredb90** [comment]
Great, thank you very much!
